



planet:
  surface-pressure: 1.0 # bar
  planet-mass: 5.972e27 # grams
  planet-radius: 6.371e8 # cm. Radius to bottom of atmosphere-grid
  surface-albedo: 0.25 # cm
  diurnal-averaging-factor: 0.5
  solar-zenith-angle: 50.0
  
opacities:
  k-distributions: [H2O, CO2]
  CIA: [CO2-CO2]
  rayleigh: [N2, CO2]
  # absorption-xs: [O2]
  photolysis-xs: [O3]
  
  
  


  

  
