


optical-properties:
  k-method: RandomOverlapResortRebin
  number-of-bins: 16
  opacities:
    solar:
      k-distributions: [H2O, CO2]
      CIA: [CO2-CO2]
      rayleigh: [N2, H2O, CO2]
    ir:
      k-distributions: [H2O, CO2, O3, CH4, CO, O2]
      CIA: [CO2-CO2, N2-N2, O2-O2, N2-O2]
      rayleigh: [H2O, CO2, O2]
      # absorption-xs: [O2]
      # photolysis-xs: [O3]

  

  
  


  

  
