
atmosphere-grid:
  number-of-layers: 100
  
planet:
  planet-mass: 5.972e27
  planet-radius: 6.371e8
  solar-zenith-angle: 60
  surface-albedo: 0.25
  
optical-properties:
  ir:
    k-method: RandomOverlapResortRebin
    number-of-bins: 16
    opacities:
      k-distributions: [H2O, CO2, CH4]
      CIA: [CO2-CO2, N2-N2, CH4-CH4, H2-CH4, H2-H2, H2O-H2O, H2O-N2]
      rayleigh: true
  solar:
    k-method: RandomOverlapResortRebin
    number-of-bins: 16
    opacities:
      k-distributions: [H2O, CO2, CH4]
      CIA: [CO2-CO2, N2-N2, CH4-CH4, H2-CH4, H2-H2, H2O-H2O, H2O-N2]
      rayleigh: true
      photolysis-xs: true
