
atmosphere-grid:
  number-of-layers: 100
  
planet:
  planet-mass: 5.972e27
  planet-radius: 6.371e8
  
optical-properties:
  ir:
    k-method: RandomOverlapResortRebin
    number-of-bins: 16
    opacities:
      k-distributions: [H2O, CO2]
      CIA: [CO2-CO2, N2-N2]
      rayleigh: [H2O, CO2, N2]
      water-continuum: MT_CKD
